version: '3'
services:
    app:
        build:
            context: .
            args:
              - NODE_ENV=development
        command: pm2-runtime server.js
        depends_on:
            - mysql
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 8080:8080
        env_file:
            - .env
        environment:
            - NODE_ENV=development
    mysql:
        image: mysql
        restart: always
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
            - ./.db:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: api
            MYSQL_USER: userapi
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - db_password
            - db_root_password
        logging:
            driver: json-file
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/opt/html
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        links:
            - app:app
        logging:
            driver: json-file
    #https://www.programonaut.com/setup-ssl-with-docker-nginx-and-lets-encrypt/
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes: 
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos
secrets:
    db_password:
        file: ./secrets/db_password.txt
    db_root_password:
        file: ./secrets/db_root_password.txt
